services:
  tar1090:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tar1090
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
      TAR1090_USER: abc
      TAR1090_PORT: ${TAR1090_PORT:-8080}
      TAR1090_SOURCE_DIR: ${TAR1090_SOURCE_DIR:-/data/readsb}
      TAR1090_WEBROOT: ${TAR1090_WEBROOT:-/usr/local/share/tar1090/html}
    volumes:
      - config:/config
      - ${TAR1090_JSON_PATH:-./sample-data}:${TAR1090_SOURCE_DIR:-/data/readsb}:ro
    ports:
      - "${TAR1090_PORT:-8080}:${TAR1090_PORT:-8080}"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges=false
    restart: ${RESTART_POLICY:-unless-stopped}
    tmpfs:
      - /tmp
      - /run:exec
    read_only: true

volumes:
  config:
    driver: local
