version: '2.4'

services:
  tar1090:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tar1090
    network_mode: host
    environment:
      TZ: Etc/UTC
      TAR1090_SOURCE_DIR: /data/readsb
    volumes:
      - config:/config
      - readsb:/data/readsb:ro
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    ports:
      - "8080:8080"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run:exec
    read_only: false
    restart: unless-stopped

volumes:
  config:
  readsb:
